# -*- coding: utf-8 -*-
"""
Created on 2025-10-22 21:39:49
---------
@summary:
---------
@author: 26644
"""

from feapder import Item


class TaxItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i tax
    """

    __table_name__ = "tax"
    __unique_key__ = ["codeTs"]
    def __init__(self, *args, **kwargs):
        self.codeTs = None
        self.gName = None
        # self.id = None
        self.impDiscountRate = None
        self.impOrdinaryRate = None
